### Objective 1: Analyzing Sales Performance

#1. What is the total sales amount generated by each sales representative?

select salesrepid, sum(totalamount) from sales group by salesrepid ;
select sales_representative.salesrepid, sum(totalamount) from sales_representative left join sales 
on sales_representative.salesrepid= sales.salesrepid  group by sales_representative.salesrepid ;

#2. How many products have been sold in each store location?
select storelocation, sum(quantity) as 'product_sold'  from sales group by storelocation order by product_sold desc ;

#3. Which product category has the highest total sales amount?
select category, sum(totalamount) from products left join  sales on products.productid = sales.productid group by category;

#4. What is the average quantity of products sold per sale?
select count(distinct productid) from sales;
select productid, round(avg(quantity),1) as 'avg_quantity' from sales group by productid order by avg_quantity desc;


#5. Which customer has made the highest number of purchases?
select sales.customerid, firstname, lastname, sum(quantity) as 'purchase'  from sales left join customers  on sales.customerid= customers.customerid
group by customerid,firstname, lastname  
order by purchase desc limit 1;

#6. What is the distribution of total sales amounts across different months?
select date, sum(totalamount) from sales where date group by date order by date ;
select date, sum(totalamount) from sales  where date > '2023-01-20' group by date order by date ;
 
#7. How does the sales performance of different regions compare?
select region, sum(totalamount) as 'total_sales' from  sales_representative left join  sales 
on sales_representative.salesrepid = sales.salesrepid group by region order by total_sales desc ;

#8. What is the total sales amount generated for each product?
select productid, sum(totalamount) from sales group by productid;

#9. What is the average sales amount per transaction?
select avg(totalamount) from sales;

#10. How many sales transactions were made by each sales representative?
select salesrepid, count(salesrepid) as 'transaction_made' from sales group by salesrepid order by salesrepid ;


### Objective 2: Customer and Product Analysis

#1. What is the average spending per customer?
select customerid, round(avg(totalamount),1) as 'avg_spend' from sales group by customerid order by customerid;

#2. Which product is the most frequently purchased by customers?
select productid, count(productid) as 'freq'  from sales group by productid order by freq desc ;

#3. How many unique customers made purchases in each city?
select storelocation, count( distinct customerid)  as 'customer' from sales group by storelocation ;

#4. What is the distribution of product categories purchased by customers?
select category, count(customerid) from products left join sales on products.productid= sales.productid  group by category;

#5. How many repeat customers are there in the dataset?
select (count(customerid )-count(distinct customerid)) from sales;
select customerid, COUNT(*) AS duplicate_count from sales group by customerid having COUNT(*) > 1;
select * from sales where customerid in (
    select customerid, COUNT(*) AS duplicate_count from sales group by customerid having COUNT(*) > 1
);
select * from sales;


#6. What is the average unit price of products purchased by customers?
select customerid, avg(totalamount/quantity) from sales group by customerid order by customerid;


#7. How does the spending behavior differ between customers from different state
select state, sum(totalamount) from customers left join sales on customers.customerid = sales.customerid group by state;

#8. Which supplier provides the most popular products?
select supplierid, sum(quantity) from sales left join products on sales.productid = products.productid  group by supplierid;


#9. What is the most common product category purchased by customers?
select category,supplierid, sum(quantity) as 'purchased'  from  products left join sales on sales.productid = products.productid 
group by category,supplierid order by purchased desc;
select distinct category from products;

#10. How many customers purchased more than one type of product?
select customerid, count( distinct productid) as "buy" from sales   group by customerid having buy >1 ;


### Objective 3: Supplier and Product Performance

#1. What is the total sales amount for each supplier?
select products.supplierid, suppliers.suppliername, sum(totalamount) from sales left join products 
on sales.productid = products.productid  
left join suppliers on products.supplierid = suppliers.supplierid 
group by products.supplierid,suppliers.suppliername;
select distinct productid from sales;

#2. Which supplier has the highest average unit price for their products?
select suppliers.supplierid, suppliername, round(avg(totalamount/quantity))  as 'avg_amount' from sales 
left join products on sales.productid = products.productid 
left join suppliers on products.supplierid = suppliers.supplierid 
group by supplierid, suppliername order by avg_amount desc;


#3. How many different products are provided by each supplier?
select supplierid, count( distinct productid) as 'no_products' from products group by supplierid;
select distinct* from  products where supplierid = 's001';

#4. What is the average total sales amount for products supplied by each supplier?
select products.supplierid, avg(totalamount) from sales left join products on sales.productid = products.productid group by supplierid;

#5. Which supplier's products have the highest total sales quantity? 
select supplierid, sum( quantity) from sales left join products on sales.productid =products.productid group by supplierid;

#6. What is the most common category of products supplied by each supplier?
-- sum of quantity of each supplier  this data is easy  otherwise we use order by
select   supplierid, category, count(quantity) from products left join sales on sales.productid = products.productid group by supplierid, category;
select * from products where category = 'tennis';

#7. How does the performance of products from different suppliers compare?
select supplierid, sum(quantity) as 'total_quantity', sum(totalamount) as 'total_ amount'  from sales left join products 
on sales.productid = products.productid group by supplierid;

#8. What is the distribution of product categories provided by each supplier?
select supplierid, category, count( products.productid) from  products group by supplierid, category order by supplierid;
select supplierid, count( distinct category) from  products group by supplierid order by supplierid;

#9. How many products from each supplier are in the top 10 best-selling products?
select supplierid, count(T1.productid) from products right join (select productid, sum(totalamount) from sales group by productid limit 10) as T1  
on T1.productid = products.productid group by supplierid ;


#10. What is the average sales amount per product category for each supplier?
select supplierid, category, round(avg(totalamount)) from sales left join products on sales.productid = products.productid group by supplierid, category;

select * from sales;
